@baseUrl = http://localhost:3333

### 1. Criar um novo produto (e salvar o ID automaticamente na memória)
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Smart TV 55 4K Samsung",
  "description": "TV LED UHD com Wi-Fi, Bluetooth e bordas infinitas",
  "price": 2899.00,
  "stock_quantity": 12
}

> {%
    client.global.set("produto_id", response.body.id);
    client.log("ID Salvo na memória: " + response.body.id);
%}



### 2. Listar todos os produtos
GET {{baseUrl}}/products



### 3. Buscar o produto específico (usando o ID salvo)
GET {{baseUrl}}/products/{{produto_id}}



### 4. Atualizar um produto (Simulando mudança de preço ou venda)
PUT {{baseUrl}}/products/{{produto_id}}
Content-Type: application/json

{
  "name": "Smart TV 55 4K Samsung",
  "description": "TV LED UHD com Wi-Fi, Bluetooth e bordas infinitas",
  "price": 2750.00,
  "stock_quantity": 11
}



### 5. Deletar o produto (usando o ID salvo e com a URL corrigida)
DELETE {{baseUrl}}/products/{{produto_id}}



### 6. Teste de Erro: Preço Negativo (Testando as travas do sistema)
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Produto Inválido",
  "description": "Teste para ver se o sistema barra",
  "price": -10.00,
  "stock_quantity": 5
}